package fordpass

// Types mostly auto-generated by https://mholt.github.io/json-to-go/

type AuthenticationResponse struct {
	AccessToken string `json:"access_token"` // Typically a JWT
	GrantID     string `json:"grant_id"`     // Typically a UUID
	TokenType   string `json:"token_type"`   // Typically `jwt`
	ExpiresIn   int    `json:"expires_in"`   // Typically `7200`
}

type VehicleCommandResponse struct {
	ID        string `json:"$id"`
	CommandID string `json:"commandId"`
	Status    int    `json:"status"`
}

type VehicleCommandStatusResponse struct {
	ID     string `json:"$id"`
	Status int    `json:"status"`
}

type VehicleStatusResponse struct {
	VehicleStatus VehicleStatus `json:"vehiclestatus"`
	Version       string        `json:"version"`
	Status        int           `json:"status"`
}
type LockStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type Alarm struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type PrmtAlarmEvent struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type Odometer struct {
	Value     float64 `json:"value"`
	Status    string  `json:"status"`
	Timestamp string  `json:"timestamp"`
}
type Fuel struct {
	FuelLevel       float64 `json:"fuelLevel"`
	DistanceToEmpty float64 `json:"distanceToEmpty"`
	Status          string  `json:"status"`
	Timestamp       string  `json:"timestamp"`
}
type Gps struct {
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
	GpsState  string `json:"gpsState"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type RemoteStart struct {
	RemoteStartDuration int    `json:"remoteStartDuration"`
	RemoteStartTime     int    `json:"remoteStartTime"`
	Status              string `json:"status"`
	Timestamp           string `json:"timestamp"`
}
type RemoteStartStatus struct {
	Value     int    `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type BatteryHealth struct {
	Value     string `json:"value"`
	Timestamp string `json:"timestamp"`
}
type BatteryStatusActual struct {
	Value     int    `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type Battery struct {
	BatteryHealth       BatteryHealth       `json:"batteryHealth"`
	BatteryStatusActual BatteryStatusActual `json:"batteryStatusActual"`
}
type Oil struct {
	OilLife       string `json:"oilLife"`
	OilLifeActual int    `json:"oilLifeActual"`
	Status        string `json:"status"`
	Timestamp     string `json:"timestamp"`
}
type TirePressure struct {
	Value     string `json:"value"`
	Timestamp string `json:"timestamp"`
}
type TirePressureByLocation struct {
	Value     int    `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type TirePressureSystemStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type DualRearWheel struct {
	Value     interface{} `json:"value"`
	Status    string      `json:"status"`
	Timestamp string      `json:"timestamp"`
}
type LeftFrontTireStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type LeftFrontTirePressure struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type RightFrontTireStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type RightFrontTirePressure struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type OuterLeftRearTireStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type OuterLeftRearTirePressure struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type OuterRightRearTireStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type OuterRightRearTirePressure struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type InnerLeftRearTireStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type InnerLeftRearTirePressure struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type InnerRightRearTireStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type InnerRightRearTirePressure struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type RecommendedFrontTirePressure struct {
	Value     interface{} `json:"value"`
	Status    string      `json:"status"`
	Timestamp string      `json:"timestamp"`
}
type RecommendedRearTirePressure struct {
	Value     interface{} `json:"value"`
	Status    string      `json:"status"`
	Timestamp string      `json:"timestamp"`
}
type TPMS struct {
	TirePressureByLocation       TirePressureByLocation       `json:"tirePressureByLocation"`
	TirePressureSystemStatus     TirePressureSystemStatus     `json:"tirePressureSystemStatus"`
	DualRearWheel                DualRearWheel                `json:"dualRearWheel"`
	LeftFrontTireStatus          LeftFrontTireStatus          `json:"leftFrontTireStatus"`
	LeftFrontTirePressure        LeftFrontTirePressure        `json:"leftFrontTirePressure"`
	RightFrontTireStatus         RightFrontTireStatus         `json:"rightFrontTireStatus"`
	RightFrontTirePressure       RightFrontTirePressure       `json:"rightFrontTirePressure"`
	OuterLeftRearTireStatus      OuterLeftRearTireStatus      `json:"outerLeftRearTireStatus"`
	OuterLeftRearTirePressure    OuterLeftRearTirePressure    `json:"outerLeftRearTirePressure"`
	OuterRightRearTireStatus     OuterRightRearTireStatus     `json:"outerRightRearTireStatus"`
	OuterRightRearTirePressure   OuterRightRearTirePressure   `json:"outerRightRearTirePressure"`
	InnerLeftRearTireStatus      InnerLeftRearTireStatus      `json:"innerLeftRearTireStatus"`
	InnerLeftRearTirePressure    InnerLeftRearTirePressure    `json:"innerLeftRearTirePressure"`
	InnerRightRearTireStatus     InnerRightRearTireStatus     `json:"innerRightRearTireStatus"`
	InnerRightRearTirePressure   InnerRightRearTirePressure   `json:"innerRightRearTirePressure"`
	RecommendedFrontTirePressure RecommendedFrontTirePressure `json:"recommendedFrontTirePressure"`
	RecommendedRearTirePressure  RecommendedRearTirePressure  `json:"recommendedRearTirePressure"`
}
type FirmwareUpgInProgress struct {
	Value     bool   `json:"value"`
	Timestamp string `json:"timestamp"`
}
type DeepSleepInProgress struct {
	Value     bool   `json:"value"`
	Timestamp string `json:"timestamp"`
}
type CcsSettings struct {
	Timestamp              string `json:"timestamp"`
	Location               int    `json:"location"`
	VehicleConnectivity    int    `json:"vehicleConnectivity"`
	VehicleData            int    `json:"vehicleData"`
	DrivingCharacteristics int    `json:"drivingCharacteristics"`
	Contacts               int    `json:"contacts"`
}
type BatteryFillLevel struct {
	Value     float64 `json:"value"`
	Status    string  `json:"status"`
	Timestamp string  `json:"timestamp"`
}
type HybridModeStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type ChargingStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type PlugStatus struct {
	Value     int    `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type ChargeStartTime struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type ChargeEndTime struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type OutandAbout struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type DriverWindowPosition struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type PassWindowPosition struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type RearDriverWindowPos struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type RearPassWindowPos struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type WindowPosition struct {
	DriverWindowPosition DriverWindowPosition `json:"driverWindowPosition"`
	PassWindowPosition   PassWindowPosition   `json:"passWindowPosition"`
	RearDriverWindowPos  RearDriverWindowPos  `json:"rearDriverWindowPos"`
	RearPassWindowPos    RearPassWindowPos    `json:"rearPassWindowPos"`
}
type RightRearDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type LeftRearDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type DriverDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type PassengerDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type HoodDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type TailgateDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}
type InnerTailgateDoor struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type DoorStatus struct {
	RightRearDoor     RightRearDoor     `json:"rightRearDoor"`
	LeftRearDoor      LeftRearDoor      `json:"leftRearDoor"`
	DriverDoor        DriverDoor        `json:"driverDoor"`
	PassengerDoor     PassengerDoor     `json:"passengerDoor"`
	HoodDoor          HoodDoor          `json:"hoodDoor"`
	TailgateDoor      TailgateDoor      `json:"tailgateDoor"`
	InnerTailgateDoor InnerTailgateDoor `json:"innerTailgateDoor"`
}

type IgnitionStatus struct {
	Value     string `json:"value"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type VehicleStatus struct {
	Vin                   string                `json:"vin"`
	LockStatus            LockStatus            `json:"lockStatus"`
	Alarm                 Alarm                 `json:"alarm"`
	PrmtAlarmEvent        PrmtAlarmEvent        `json:"PrmtAlarmEvent"`
	Odometer              Odometer              `json:"odometer"`
	Fuel                  Fuel                  `json:"fuel"`
	Gps                   Gps                   `json:"gps"`
	RemoteStart           RemoteStart           `json:"remoteStart"`
	RemoteStartStatus     RemoteStartStatus     `json:"remoteStartStatus"`
	Battery               Battery               `json:"battery"`
	Oil                   Oil                   `json:"oil"`
	TirePressure          TirePressure          `json:"tirePressure"`
	Authorization         string                `json:"authorization"`
	TPMS                  TPMS                  `json:"TPMS"`
	FirmwareUpgInProgress FirmwareUpgInProgress `json:"firmwareUpgInProgress"`
	DeepSleepInProgress   DeepSleepInProgress   `json:"deepSleepInProgress"`
	CcsSettings           CcsSettings           `json:"ccsSettings"`
	LastRefresh           string                `json:"lastRefresh"`
	LastModifiedDate      string                `json:"lastModifiedDate"`
	ServerTime            string                `json:"serverTime"`
	BatteryFillLevel      BatteryFillLevel      `json:"batteryFillLevel"`
	HybridModeStatus      HybridModeStatus      `json:"hybridModeStatus"`
	ChargingStatus        ChargingStatus        `json:"chargingStatus"`
	PlugStatus            PlugStatus            `json:"plugStatus"`
	ChargeStartTime       ChargeStartTime       `json:"chargeStartTime"`
	ChargeEndTime         ChargeEndTime         `json:"chargeEndTime"`
	OutandAbout           OutandAbout           `json:"outandAbout"`
	WindowPosition        WindowPosition        `json:"windowPosition"`
	DoorStatus            DoorStatus            `json:"doorStatus"`
	IgnitionStatus        IgnitionStatus        `json:"ignitionStatus"`

	// Unknown types -- please contribute if you can!
	ElVehDTE                      interface{} `json:"elVehDTE"`
	PreCondStatusDsply            interface{} `json:"preCondStatusDsply"`
	ChargerPowertype              interface{} `json:"chargerPowertype"`
	BatteryPerfStatus             interface{} `json:"batteryPerfStatus"`
	BatteryChargeStatus           interface{} `json:"batteryChargeStatus"`
	DcFastChargeData              interface{} `json:"dcFastChargeData"`
	BatteryTracLowChargeThreshold interface{} `json:"batteryTracLowChargeThreshold"`
	BattTracLoSocDDsply           interface{} `json:"battTracLoSocDDsply"`
	DieselSystemStatus            interface{} `json:"dieselSystemStatus"`
}
